ecommerce/api/urls.py
from django.urls import path, include
# from api.products import products_view
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from api.products import ProductViewSet
from api.profile import profile_view

router = DefaultRouter()
router.register('products', ProductViewSet)

urlpatterns = [
    path('authenticate/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('products/', products_view),
    path('', include(router.urls)),
    path('profile/', profile_view),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt


def homepage(request):
    return render(request, 'homepage.html')


urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('users.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/orders/urls.py
from django.urls import path
from orders.views import show_cart, add_to_cart, update_cart, checkout, pay

app_name = 'orders'

urlpatterns = [
    path('cart/', show_cart, name='cart'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/update/', update_cart, name='update_cart'),
    path('checkout/', checkout, name='checkout'),
    path('pay/<int:order_id>/', pay, name='pay'),
]

ecommerce/products/urls.py
from django.urls import path
from products.views import show_all_products, show_product, show_all_categories

app_name = 'products'

# all routes below are prefixed with `products/`
urlpatterns = [
    path('', show_all_products, name='all_products'),  # products/
    path('<int:product_id>/', show_product, name='product_details'),  # products/<int>/,
    path('categories/', show_all_categories, name='all_categories'),
]

ecommerce/products/models.py
from django.db import models
from django.contrib.auth import get_user_model
# from django.conf import settings
from django.templatetags.static import static
from itertools import groupby

AuthUser = get_user_model()


class SpecificationCategory(models.Model):
    name = models.CharField(max_length=128, unique=True, null=False)


class Specification(models.Model):
    class Meta:
        unique_together = ('specification_category', 'name')

    specification_category = models.ForeignKey(SpecificationCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, null=False)
    value = models.TextField(null=False)

    def __str__(self):
        return self.name


class Category(models.Model):
    class Meta:
        verbose_name_plural = 'categories'

    parent = models.ForeignKey('Category', on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(max_length=128, null=False, unique=True)

    def __str__(self):
        return self.name


class Store(models.Model):
    name = models.CharField(max_length=128, unique=True, null=False)
    # owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    owner = models.ForeignKey(AuthUser, on_delete=models.CASCADE)
    logo = models.ImageField(upload_to='stores/', null=True, default=None, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    class Meta:
        ordering = ('name', '-price')

    store = models.ForeignKey(Store, on_delete=models.SET_NULL, default=None, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, default=None, null=True)
    name = models.CharField(max_length=255, null=False, unique=True)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=False)  # 9999.99
    specifications = models.ManyToManyField(Specification)
    image = models.ImageField(upload_to='products/', null=True, default=None)

    @property
    def image_url(self):
        if self.image:
            return self.image.url

        return static('images/product_placeholder.webp')

    def __str__(self):
        return self.name

    def specs_categories(self):
        grouped_specs = groupby(self.specifications.all(), key=lambda specs: specs.specification_category.name)

        # for specs_category_name, group in grouped_specs:
        #     print(specs_category_name, list(group))

        return ((specs_category_name, list(group)) for specs_category_name, group in grouped_specs)

ecommerce/products/views.py
from django.shortcuts import render, Http404, get_object_or_404
from django.core.paginator import Paginator
from products.models import Product, Category


def show_all_products(request):
    page = request.GET.get('page', 1)

    products = Product.objects.all()

    paginator = Paginator(products, 16)
    paginated_products = paginator.get_page(page)

    return render(request, 'products/all_products.html', {
        'paginated_products': paginated_products,
    })


def show_product(request, product_id):
    # product = Product.objects.get(id=product_id)
    # try:
    #     product = Product.objects.get(pk=product_id)
    # except Product.DoesNotExist:
    #     raise Http404('Product not found')
    # product = get_object_or_404(Product, id=product_id)
    product = get_object_or_404(Product, pk=product_id)

    return render(request, 'products/product.html', {
        'product': product
    })


def show_all_categories(request):
    page = request.GET.get('page', 1)

    cateogries = Category.objects.all()

    paginator = Paginator(cateogries, 10)
    paginated_categories = paginator.get_page(page)

    return render(request, 'products/all_categories.html', {
        'paginated_categories': paginated_categories,
    })

ecommerce/products/templates/products/all_categories.html
{% extends 'base.html' %}

{% block title %}
    <title>Available Categories</title>
{% endblock %}

{% block content %}
    {% include 'pagination.html' with pagination=paginated_categories %}
    <ul>
        {% for category in paginated_categories %}
            <li>{{ category.name }}</li>
        {% empty %}
            <p>No category available.</p>
        {% endfor %}
    </ul>
    {% include 'pagination.html' with pagination=paginated_categories %}
{% endblock %}

ecommerce/products/templates/products/all_products.html
{% extends 'base.html' %}

{% block title %}
    <title>Available Products</title>
{% endblock %}

{% block content %}
    {% url 'products:all_products' as pagination_url %}
    {% include 'pagination.html' with pagination=paginated_products url=pagination_url %}
    <ul class="products-container">
        {% for product in paginated_products %}
            <li>
                <img src="{{ product.image_url }}" width="100%" />
                <a href="{% url 'products:product_details' product.id %}">
                    <p>{{ product.name | truncatechars:200 }}</p>
                </a>
                <div class="product-data">
                    <p class="price">{{ product.price }} RON</p>
                    <form method="post" action="{% url 'orders:add_to_cart' product.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="next" value="{% url 'products:all_products' %}" />
                        <input type="submit" value="Add to cart" />
                    </form>
                </div>
            </li>
        {% empty %}
            <p>No products available.</p>
        {% endfor %}
    </ul>
    {% include 'pagination.html' with pagination=paginated_products url=pagination_url %}
{% endblock %}

ecommerce/products/templates/products/product.html
{% extends 'base.html' %}

{% block title %}
    <title>{{ product.name }}</title>
{% endblock %}

{% block content %}
    <div class="product-metadata">
        <div class="product-image-container">
            <img src="https://s13emagst.akamaized.net/products/39979/39978446/images/res_aee79fd657ad22d14453cfa755a0ee8a.jpg?width=450&height=450&hash=68A6C989D8B50C687C47C4AE9ABBAF20" width="100%" />
        </div>
        <div class="product-details">
            <p id="product-name">{{ product.name }}</p>
            <div class="product-controls">
                <p>{{ product.price }} RON</p>
                <button>Add to cart</button>
            </div>
        </div>
    </div>
    {% for specs_category_name, specs in product.specs_categories %}
        <table class="product-specifications">
            <thead>
                <tr>
                    <th colspan="2">{{ specs_category_name }}</th>
                </tr>
            </thead>
            <tbody>
                {% for spec in specs %}
                    <tr>
                        <td>{{ spec.name }}</td>
                        <td>{{ spec.value }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endfor %}
{% endblock %}