ecommerce/api/urls.py
from django.urls import path, include
# from api.products import products_view
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from api.products import ProductViewSet
from api.profile import profile_view

router = DefaultRouter()
router.register('products', ProductViewSet)

urlpatterns = [
    path('authenticate/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('products/', products_view),
    path('', include(router.urls)),
    path('profile/', profile_view),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt


def homepage(request):
    return render(request, 'homepage.html')


urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('users.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/orders/urls.py
from django.urls import path
from orders.views import show_cart, add_to_cart, update_cart, checkout, pay

app_name = 'orders'

urlpatterns = [
    path('cart/', show_cart, name='cart'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/update/', update_cart, name='update_cart'),
    path('checkout/', checkout, name='checkout'),
    path('pay/<int:order_id>/', pay, name='pay'),
]

ecommerce/orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from products.models import Product

AuthUser = get_user_model()


class Order(models.Model):
    user = models.ForeignKey(AuthUser, null=True, default=None, on_delete=models.SET_NULL)
    billing_address = models.CharField(max_length=128)
    shipping_address = models.CharField(max_length=128)
    created_at = models.DateTimeField(default=timezone.now)

    @property
    def total_price(self):
        total = 0

        for order_product in self.products.all():
            total += order_product.price * order_product.quantity

        return total

    def __str__(self):
        return f'<Order {self.id}>'


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='products')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    price = models.DecimalField(max_digits=6, decimal_places=2, null=False)

    def __str__(self):
        return f'<OrderProduct {self.id}>'

ecommerce/orders/forms.py
from django import forms
from products.models import Product
from orders.models import Order, OrderProduct


class CartForm(forms.Form):
    def __init__(self, *args, session=None, **kwargs):
        if not session:
            raise ValueError('Session is not defined.')
        self._session = session

        super().__init__(*args, **kwargs)

        cart = self._session.get('cart', {})
        self._products = Product.objects.filter(id__in=cart.keys())
        for product in self._products:
            product_key = str(product.id)
            self.fields[product_key] = forms.IntegerField(
                label=product.name,
                min_value=0,
                step_size=1,
                initial=cart[product_key]
            )

    @property
    def products(self):
        return self._products

    # my_instance.products <> my_instance.products()

    def clean(self):
        print('cleaned_data', self.cleaned_data)

        for product_key, quantity in self.cleaned_data.items():
            try:
                product = Product.objects.get(id=product_key)
            except Product.DoesNotExist:
                product = None

            if not product:
                raise forms.ValidationError(f'Product with key = {product_key} is not available.')

        return self.cleaned_data

    def save(self):
        self._session['cart'] = {
            product_key: quantity
            for product_key, quantity in self.cleaned_data.items()
            if quantity >= 1
        }
        # self._session.modified = True


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('billing_address', 'shipping_address')

    def __init__(self, *args, cart=None, user=None, **kwargs):
        super().__init__(*args, **kwargs)

        self._cart = cart
        self._user = user

    def save(self, commit=True):
        order = super().save(commit=False)
        if self._user:
            order.user = self._user

        if commit:
            order.save()

            for product_key, quantity in self._cart.items():
                product = Product.objects.get(id=product_key)

                order_product = OrderProduct(
                    order=order,
                    product=product,
                    quantity=quantity,
                    price=product.price
                )
                order_product.save()

        return order

ecommerce/orders/views.py
import stripe
from django.shortcuts import render, redirect, reverse, Http404, get_object_or_404, HttpResponse
from django.contrib import messages
from django.conf import settings
from products.models import Product
from orders.models import Order
from orders.forms import CartForm, OrderForm


def show_cart(request):
    form = CartForm(session=request.session)

    return render(request, 'orders/cart.html', {
        'form': form
    })


def add_to_cart(request, product_id):
    if request.method == 'GET':
        raise Http404('Method not allowed.')

    product = get_object_or_404(Product, pk=product_id)

    cart_product_key = str(product_id)
    next_url = request.POST.get('next')

    if 'cart' not in request.session:
        request.session['cart'] = {}

    if cart_product_key not in request.session['cart']:
        request.session['cart'][str(product_id)] = 1

    # request.session.modified = True

    messages.add_message(request, messages.SUCCESS, f"Product {product.name} was successfully added to the cart.")

    if next_url:
        return redirect(next_url)

    return redirect(reverse('orders:cart'))


def update_cart(request):
    if request.method == 'GET':
        raise Http404('Method not allowed.')

    form = CartForm(session=request.session, data=request.POST)
    if form.is_valid():
        form.save()

        messages.add_message(request, messages.SUCCESS, 'Cart was successfully updated.')
    else:
        messages.add_message(request, messages.ERROR, 'Something went wrong! Try again later.')

    return redirect(reverse('orders:cart'))


def checkout(request):
    cart = request.session.get('cart', {})

    if len(cart.keys()) == 0:
        return redirect(reverse('homepage'))

    products = Product.objects.filter(id__in=cart.keys())
    total_price = sum([
        product.price * cart[str(product.id)]
        for product in products
    ])

    if request.method == 'GET':
        form = OrderForm()
    else:
        cart = request.session.get('cart', {})
        user = request.user if request.user.is_authenticated else None
        form = OrderForm(data=request.POST, cart=cart, user=user)

        if form.is_valid():
            order = form.save()
            request.session['cart'] = {}
            # request.session.modified = True
            return redirect(reverse('orders:pay', args=(order.id,)))

    return render(request, 'orders/checkout.html', {
        'form': form,
        'total_price': total_price
    })


def pay(request, order_id):
    order = get_object_or_404(Order, pk=order_id)

    # if order.payment_fulfilled:
    #     return redirect(reverse('homepage'))

    if request.method == 'POST':
        if request.POST['status'] == 'error':
            # order.status = 'payment_failed'
            messages.add_message(request, messages.ERROR, "Something went wrong! Please try another payment method.")
            return redirect(reverse('orders:pay', args=(order.id,)))
        else:
            # order.status = 'payment_fulfilled'
            messages.add_message(request, messages.SUCCESS, "You completed your payment. Thank you for your money! :evil_imp:")
            return redirect(reverse('products:all_products'))

    payment_intent = stripe.PaymentIntent.create(
        amount=int(order.total_price * 100),
        currency='ron',
        # Verify your integration in this guide by including this parameter
        metadata={'integration_check': 'accept_a_payment'},
        api_key=settings.STRIPE_SECRET_KEY
    )

    return render(request, 'orders/pay.html', {
        'order': order,
        'stripe_public_key': settings.STRIPE_PUBLIC_KEY,
        'client_secret': payment_intent['client_secret']
    })

ecommerce/orders/templates/orders/cart.html
{% extends 'base.html' %}
{% load orders %}

{% block content %}
    <form method="post" action="{% url 'orders:update_cart' %}">
        {% csrf_token %}
        <table style="width: 100%;">
            <thead>
                <th>Product name</th>
                <th>Quantity</th>
                <th>Price per item</th>
                <th>Total price</th>
            </thead>
            <tbody>
                {% for field in form %}
                    {% cart_form_data form forloop.counter0 as product_details %}
                    <tr>
                        <td>{{ field.label | truncatechars:50 }}</td>
                        <td>{{ field }}</td>
                        <td>{{ product_details.price_per_item }} RON</td>
                        <td>{{ product_details.total_price }} RON</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="4" style="text-align: center">No products in cart.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% if form.fields|length > 0 %}
            <input type="submit" value="Update cart" />
        {% endif %}
    </form>
    <p style="font-weight: bold">
        Total price: {% total_price form %} RON
    </p>
    {% if form.fields|length > 0 %}
        <a href="{% url 'orders:checkout' %}">Go to checkout</a>
    {% endif %}
{% endblock %}

ecommerce/orders/templates/orders/checkout.html
{% extends 'base.html' %}

{% block title %}
    <title>Checkout page</title>
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'orders:checkout' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <p style="font-weight: bold;">Total price: {{ total_price }} RON</p>
        <input type="submit" value="Order" />
    </form>
{% endblock %}

ecommerce/orders/templates/orders/pay.html
{% extends 'base.html' %}

{% block title %}
    <title>Pay order #{{ order.id }}</title>
{% endblock %}

{% block javascript %}
    <script src="https://js.stripe.com/v3/"></script>
    <script>
        window.onload = function () {
            var stripe = Stripe('{{ stripe_public_key }}');
            // Set up Stripe.js and Elements to use in checkout form
            var elements = stripe.elements();
            var style = {
                base: {
                    color: "#3  2325d",
                }
            };

            var card = elements.create("card", {hidePostalCode: true, style: style});
            card.mount("#card-element");

            card.on('change', ({error}) => {
                let displayError = document.getElementById('card-errors');
                if (error) {
                    displayError.textContent = error.message;
                } else {
                    displayError.textContent = '';
                }
            });

            var form = document.getElementById('payment-form');
            form.addEventListener('submit', function (ev) {
                ev.preventDefault();
                // If the client secret was rendered server-side as a data-secret attribute
                // on the <form> element, you can retrieve it here by calling `form.dataset.secret`
                stripe.confirmCardPayment("{{ client_secret }}", {
                    payment_method: {
                        card: card,
                        billing_details: {
                            name: 'Jenny Rosen'
                        }
                    }
                }).then(function (result) {
                    console.log('result', result);

                    var statusElement = document.querySelector('#payment-status')
                    if (result.error) {
                        statusElement.value = 'error'
                    } else {
                        // The payment has been processed!
                        if (result.paymentIntent.status === 'succeeded') {
                            statusElement.value = 'succeeded'
                        }
                    }

                    document.querySelector('#payment-form').submit()
                });
            });
        };
    </script>
{% endblock %}

{% block content %}
    <p>We're requesting a payment of {{ order.total_price }} RON through our Stripe partner.</p>
    <form id="payment-form" method="post" action="{% url 'orders:pay' order.id %}">
        {% csrf_token %}
        <input id="payment-status" type="hidden" name="status" />

        <div id="card-element">
            <!-- Elements will create input elements here -->
        </div>

        <!-- We'll put the error messages in this element -->
        <div id="card-errors" role="alert"></div>

        <button type="submit">Submit Payment</button>
    </form>
{% endblock %}