ecommerce/api/urls.py
from django.urls import path, include
# from api.products import products_view
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)
from api.products import ProductViewSet
from api.profile import profile_view

router = DefaultRouter()
router.register('products', ProductViewSet)

urlpatterns = [
    path('authenticate/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    # path('products/', products_view),
    path('', include(router.urls)),
    path('profile/', profile_view),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import render
from django.conf import settings
from django.conf.urls.static import static
from django.views.decorators.csrf import csrf_exempt


def homepage(request):
    return render(request, 'homepage.html')


urlpatterns = [
    path('', homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', include('users.urls')),
    path('orders/', include('orders.urls')),
    path('api/', include('api.urls')),
]

if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/orders/urls.py
from django.urls import path
from orders.views import show_cart, add_to_cart, update_cart, checkout, pay

app_name = 'orders'

urlpatterns = [
    path('cart/', show_cart, name='cart'),
    path('cart/add/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/update/', update_cart, name='update_cart'),
    path('checkout/', checkout, name='checkout'),
    path('pay/<int:order_id>/', pay, name='pay'),
]

ecommerce/products/urls.py
from django.urls import path
from products.views import show_all_products, show_product, show_all_categories

app_name = 'products'

# all routes below are prefixed with `products/`
urlpatterns = [
    path('', show_all_products, name='all_products'),  # products/
    path('<int:product_id>/', show_product, name='product_details'),  # products/<int>/,
    path('categories/', show_all_categories, name='all_categories'),
]

ecommerce/users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView
from users.views import profile_view, register_view

app_name = 'users'


urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('', include('django.contrib.auth.urls')),
    path('profile/', profile_view, name='profile'),
    path('register/', register_view, name='register'),
]

ecommerce/templates/base.html
{% load static %}

<html>
    <head>
        {% block title %}{% endblock %}
        {% block javascript %}{% endblock %}
        <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    </head>
    <body>
        <div class="header">
            <img src="{% static 'images/logo.png' %}" height="100%" />
            {% include 'navigation.html' %}
        </div>
        <div class="notifications">
            {% include 'notifications.html' %}
        </div>
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

ecommerce/templates/homepage.html
{% extends 'base.html' %}

{% block title %}
    <title>Homepage</title>
{% endblock %}

{% block content %}
    <p>Hey, welcome to my first web app!</p>
    <p>User data: {{ user.first_name }} {{ user.last_name }}</p>
{% endblock %}

ecommerce/templates/navigation.html
{% load orders %}

{% cart_data as cart_data %}

<nav>
    <a href="{% url 'homepage' %}">Homepage</a>
    <a href="{% url 'products:all_categories' %}">Categories</a>
    <a href="{% url 'products:all_products' %}">Products</a>
    {% comment %}<a href="{% url 'orders:cart' %}">Cart ({{ request.session.cart | total_products }})</a>{% endcomment %}
    <a href="{% url 'orders:cart' %}" title="{{ cart_data.total_amount }}">Cart ({{ cart_data.total_products }})</a>
    {% if user.is_authenticated %}
        <a href="{% url 'users:profile' %}">Profile</a>
        <form method="post" action="{% url 'users:logout' %}">
            {% csrf_token %}
            <input type="submit" value="Logout" />
        </form>
    {% else %}
        <a href="{% url 'users:register' %}">Register</a>
        <a href="{% url 'users:login' %}">Login</a>
    {% endif %}
</nav>

ecommerce/templates/notifications.html
{% if messages %}
    <ul class="messages">
        {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
{% endif %}

ecommerce/templates/pagination.html
{% load pagination %}

<div>
    {% comment %}<br/>
    <br/>
    <br/>
    <br/>
    <p>{{ "my product" | capfirst }}</p>
    <p>my product{{ 1 | pluralize }}</p>
    <p>{{ "my product" | my_custom_filter }}</p>
    <p>my product{{ 1 | my_custom_filter }}</p>
    <p>2 + 3 = {{ 2 | add:3 }}</p>
    <p>2 + 3 = {{ 2 | add_filter:3 }}</p>
    <br/>
    <br/>
    <br/>
    <br/>{% endcomment %}
    <a href="{{ url }}?page=1">
        First page (1)
    </a>
    {% if pagination.has_previous %}
        <a href="{{ url }}?page={{ pagination.previous_page_number }}">
            Previous page ({{ pagination.previous_page_number }})
        </a>
    {% endif %}
    <span>Current page: {{ pagination.number }}</span>
    {% if pagination.has_next %}
        <a href="{{ url }}?page={{ pagination.next_page_number }}">
            Next page ({{ pagination.next_page_number }})
        </a>
    {% endif %}
    <a href="{{ url }}?page={{ pagination.paginator.num_pages }}">
        Last page ({{ pagination.paginator.num_pages }})
    </a>
</div>